### ISSUE TITLE
Not loading with OpenPHT

### ISSUE THREAD

**Issue by ghost** [magnumdoomguy/skin.aeon.nox.5#13]
As a long time Kodi user I was so happy to see this skin. I do use OpenPHT, and when I initialized the skin, after leaving the settings screen, I get the bar across the bottom third, with my username and the time, but none of the menu selections. I had to delete the skin out of the directory so I could "get back in".

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/16200417/24339499/f876de2e-1279-11e7-828e-400d483a7193.JPG)

**Comment by dan-the-man-nz** [comment]
what version and OS of openpht are you running?
what version of the skin is that? did you install from within openpht?

**Comment by ghost** [comment]
Gosh, I'm sorry.

1.6.2 on Windows 10. The AN skin is 5.4.0

I wasn't aware that I could install from within, so I just dropped this into the OpenPHT addon folder.

**Comment by dan-the-man-nz** [comment]
that is a very old version of openpht, and its not designed to use that 5.4.0 skin, the 5.4.0 skin needs Openpht 1.8.0  (besides the fact you tried to do it manually as well)

delete that nox folder you downloaded from openpht
update openpht to 1.8.0
install nox from inside openpht under system, appearance, skin

should be fine after that, reply back if its not, i will close the issue for now

https://forums.plex.tv/discussion/264250/release-aeon-nox-5-4-0/p1

**Comment by ghost** [comment]
Ok. I was sticking with 1.6 because it was the last stable version, so I'll give 1.8 a try.

**Comment by dan-the-man-nz** [comment]
1.8.0 works great on windows, its definitely better than 1.6.2, lots of new features and some pretty big bugs are fixed with transcoding etc

(i also use windows 10 for my htpc's)

**Comment by ghost** [comment]
Thanks for clearing that up, Dan. It installed and works like a dream. Way easier to install in-client.

**Comment by dan-the-man-nz** [comment]
no prob.

check out the new menu customiser in Nox 5.4.0 !

catchas
