### ISSUE TITLE
FEATURE REQUEST - Kodi Skin

### ISSUE THREAD

**Issue by qazero** [magnumdoomguy/skin.aeon.nox.5#15]
I love the screenshots. Is it possible to port this to be a compatible Kodi skin?

**Comment by dan-the-man-nz** [comment]
this is ported to OpenPHT/Rasplex FROM the Kodi Aeon Nox skin, 

here are the kodi links
http://kodi.wiki/view/Add-on:Aeon_Nox
https://github.com/BigNoid/Aeon-Nox

**Comment by qazero** [comment]
I am using the Aeon Nox Kodi skin currently. What did you use to for the On Deck and Recently Added home shelf widgets? Also, how did you get the video info to display in the layout in your 4th screenshot (screenshot4.png)?

**Comment by dan-the-man-nz** [comment]
this skin is modified for openpht/rasplex, they are plex api / feature of openpht/rasplex clients

if you like those features you should ask the kodi nox developer about the possibilities

or you scrap kodi and come to plex :)

**Comment by qazero** [comment]
I am also a plex user ;)

I just wish OpenPHT supported android and roku too :/

**Comment by dan-the-man-nz** [comment]
sell them :)
